name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c RELEASE --no-restore
    - name: Test
      run: dotnet test -c RELEASE --no-build --verbosity normal
    - name: Publish
      run: dotnet publish -c RELEASE ./src/DeviceService/Server/DeviceService.Server.csproj -o ./publish
    - uses: actions/upload-artifact@v2
      with:
        name: deployment
        path: publish
