name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  AZURE_WEBAPP_NAME: iothubblazorsample   # set this to your application's name
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c RELEASE --no-restore
    - name: Test
      run: dotnet test -c RELEASE --no-build --verbosity normal
    - name: Publish
      run: dotnet publish -c RELEASE ./src/DeviceService/Server/DeviceService.Server.csproj -o ./publish
    - uses: actions/upload-artifact@v2
      with:
        name: deployment
        path: publish
    - uses: azure/webapps-deploy@v2
      with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }} # Define secret variable in repository settings as per action documentation
          package: publish
        
